name: build and publish containers
on: workflow_dispatch
permissions:
  packages: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v4
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to github container repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build+push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:local-ca"
          push: true
          tags: ghcr.io/openchami/local-ca:acme
