# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
#
# SPDX-License-Identifier: MIT

name: Cleanup
on:
  pull_request:
    types: [closed]

permissions:
  packages: write

jobs:
  cleanup:
    uses: OpenCHAMI/github-actions/.github/workflows/pr-registry-cleanup.yml@0874861a34e9835641ae96fea2904643cc727824 # seantronsen/feat/add-missing-workflows